version: 0.2

phases:
  install:
    commands:
      - echo "Setting up AWS CodeArtifact auth"
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain produccion --domain-owner 851725425623 --region us-east-1 --query authorizationToken --output text`
      - npm config set //produccion-851725425623.d.codeartifact.us-east-1.amazonaws.com/npm/demo-nodejs-npm/:_authToken=${CODEARTIFACT_AUTH_TOKEN}
      - npm install

  build:
    commands:
      - npm test

artifacts:
  files:
    - '**/*'
